name: CI Pipeline with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Lint Backend
        working-directory: node-js-server
        run: |
          npm install
          npm run lint || echo "Lint issues found"

     
      - name: Lint Frontend
        working-directory: angular-12-client
        run: |
          npm install
          npm run lint || echo "Lint issues found"

     
      - name: Build Angular Frontend
        working-directory: angular-12-client
        run: npm run build -- --prod

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Check Azure Account
        run: az account show    

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

   
      - name: Build Backend Docker Image
        working-directory: node-js-server
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

  
      - name: Build Frontend Docker Image
        working-directory: angular-12-client
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

    #  - name: Set Azure environment variables
      #  run: |
        #  echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        #  echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        #  echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        #  echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
    

      - name: Terraform Init & Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group test-opus-rg --name myAKSCluster
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/mysql-deployment.yaml

    
      